#! perl

#script to copy/paste text in URXVT
#copy to one othe the following locations depending on your system
#/usr/lib/x86_64-linux-gnu/urxvt/perl/clipboard
#/usr/lib/urxvt/perl/clipboard

sub on_sel_grab {
    my $query = $_[0]->selection;
    open (my $pipe,'| /usr/bin/xclip -in -selection clipboard') or die;
    print $pipe $query;
    close $pipe;
}
sub paste {
    my ($self) = @_;
    my $content = `/usr/bin/xclip -loop 1 -out -selection clipboard` ;
    $self->tt_write ($content);
}
sub on_user_command {
    my ($self, $cmd) = @_;
    if ($cmd eq "clipboard:paste") {
        $self->paste;
    }
}
